### ISSUE TITLE
Not working for me so far after new update.

### ISSUE THREAD

**Issue by tigerman325** [ToadKing/apple-music-barcode-isrc#1]
First try after updating and I get the following message "ReferenceError: GM_xmlhttpRequest is not defined" then after clicking the Blue "OK" button all I get is a blank pop up that only has the message "Loading, press ESC to close..." and nothing else. Not sure if this is related to your token explanation or not.

**Comment by ToadKing** [comment]
What browser and userscript manager are you using?

**Comment by tigerman325** [comment]
I’m using Microsoft Edge v106.0.1370.52 (64-bit) & Tampermonkey v4.16.1

**Comment by tigerman325** [comment]
I just tried it on my Google Chrome Version 107.0.5304.63 (64-bit) with Tampermonkey as well, and the identical issue happens.

Marc

**Comment by ToadKing** [comment]
Try version 0.14 I just pushed.

**Comment by tigerman325** [comment]
It works!!! Awesome, thanks.

Marc

**Comment by tigerman325** [comment]
OK, it works on Chrome now, but still not on Edge, but I don’t mind using that if I need to.

**Comment by tigerman325** [comment]
Ok., It works on both. I forgot to update it on my Edge first, lol. Sorry.
